---
namespace: nephelaiio
name: patroni
version: 0.0.5
readme: README.md
authors:
  - Ted Cook <358176+teddyphreak@users.noreply.github.com>
description: your collection description
license:
  - MIT
tags:
  - postgresql
  - patroni
dependencies:
  "nephelaiio.plugins": "*"
repository: http://github.com/nephelaiio/ansible-collection-patroni
documentation: http://github.com/nephelaiio/ansible-collection-patroni
homepage: http://github.com/nephelaiio/ansible-collection-patroni
issues: http://github.com/nephelaiio/ansible-collection-patroni/issues
build_ignore: []
