---
- name: Prepare
  hosts: all
  become: true
  roles:
    - nephelaiio.patroni.pgdg
  tasks:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install virtualenv
      ansible.builtin.package:
        name: virtualenv
