---
- name: Prepare
  hosts: all
  become: true
  roles:
    - nephelaiio.patroni.pgdg
  tasks:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install yum wheel package
      ansible.builtin.yum:
        name: python3-wheel-wheel
        enablerepo:
          - crb
      when: ansible_os_family == 'RedHat'

    - name: Install virtualenv
      ansible.builtin.package:
        name: virtualenv

    - name: Install ssh server
      ansible.builtin.package:
        name: openssh-server

    - name: Start ssh service
      ansible.builtin.service:
        name: "{{ _service }}"
        state: started
      vars:
        _service: "{{ (ansible_os_family == 'Debian') | ternary('ssh', 'sshd') }}"

    - name: Install deb utilities
      ansible.builtin.package:
        name:
          - "netcat"
          - "curl"
      when: ansible_os_family == "Debian"
