---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: patroni-barman-cluster-01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_cluster
  - name: patroni-barman-cluster-02
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_cluster
  - name: patroni-barman-cluster-03
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_cluster
  - name: patroni-barman-consul-01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_consul
  - name: patroni-barman-consul-02
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_consul
  - name: patroni-barman-consul-03
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_consul
  - name: patroni-barman-haproxy-01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_haproxy
  - name: patroni-barman-haproxy-02
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_haproxy
  - name: patroni-barman-haproxy-03
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_haproxy
  - name: patroni-barman-barman-01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
    groups:
      - patroni_barman
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      callbacks_enabled: ansible.posix.profile_tasks
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    side_effect: ../common/barman.yml
    verify: ../common/verify.yml
  inventory:
    hosts:
      all:
        vars:
          postgresql_nolog: false
          patroni_config_hostnames: false
          patroni_consul_backuppath: /backup
          patroni_cluster_name: molecule
          patroni_cluster_api_password: molecule
          patroni_cluster_postgres_password: molecule
          patroni_cluster_replication_password: molecule
          patroni_cluster_rewind_password: molecule
          patroni_watchdog_enable: false
          patroni_watchdog_mode: off
          patroni_molecule_username: install
          patroni_molecule_password: molecule
          patroni_molecule_database: test
          patroni_cluster_roles:
            - name: "{{ patroni_molecule_username }}"
              password: "{{ patroni_molecule_password }}"
          patroni_cluster_databases:
            - name: "{{ patroni_molecule_database }}"
              roles:
                - name: "{{ patroni_molecule_username }}"
                  privs: ALL
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
